<?xml version="1.0" encoding="utf-8"?><Database Name="library" Class="LibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-ID9HRR5;Initial Catalog=library;Integrated Security=True" SettingsObjectName="Library.Data.Properties.Settings" SettingsPropertyName="libraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Reader" Member="Readers">
    <Type Name="Reader">
      <Column Name="reader_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="reader_f_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="reader_l_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Reader_Event" Member="Events" ThisKey="reader_id" OtherKey="reader" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="book_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="publishment_year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="genre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Book_Event" Member="Events" ThisKey="book_id" OtherKey="book" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Events">
    <Type Name="Event">
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="event_time" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="is_borrowing_event" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="book" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reader" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Book_Event" Member="Book1" ThisKey="book" OtherKey="book_id" Type="Book" IsForeignKey="true" />
      <Association Name="Reader_Event" Member="Reader1" ThisKey="reader" OtherKey="reader_id" Type="Reader" IsForeignKey="true" />
    </Type>
  </Table>
</Database>